export const icon = {
  angleRight: 'las la-angle-right',
  bell: 'las la-bell',
  checkCircle: 'las la-check-circle',
  clone: 'las la-clone',
  deployments: 'las la-cloud-upload-alt',
  environments: 'las la-layer-group',
  externalLink: 'las la-external-link-square-alt',
  features: 'las la-flag',
  home: 'las la-home',
  mapMarked: 'las la-map-marked',
  mountain: 'las la-mountain',
  plus: 'las la-plus',
  plusCircle: 'las la-plus-circle',
  projects: 'las la-cubes',
  releases: 'las la-code-branch',
  shippingFast: 'las la-shipping-fast',
  spinner: 'las la-circle-notch',
  stream: 'las la-stream',
  tasks: 'las la-tasks',
  timesCircle: 'las la-times-circle',
  user: 'las la-user',
  variables: 'las la-tags',
};
