export const icon = {
  bell: 'las la-bell',
  checkCircle: 'las la-check-circle',
  clone: 'las la-clone',
  deploy: 'las la-cloud-upload-alt',
  mountain: 'las la-mountain',
  plus: 'las la-plus',
  plusCircle: 'las la-plus-circle',
  projects: 'las la-cubes',
  shippingFast: 'las la-shipping-fast',
  spinner: 'las la-spinner',
  stream: 'las la-stream',
  tasks: 'las la-tasks',
  timesCircle: 'las la-times-circle',
  user: 'las la-user',
} as Record<string, string>;
