export { default as iconStyles } from './icon.module.css';

export const icon = {
  angleRight: 'las la-angle-right',
  bell: 'las la-bell',
  clone: 'las la-clone',
  close: 'las la-times',
  copy: 'las la-copy',
  deployments: 'las la-cloud-upload-alt',
  environments: 'las la-layer-group',
  error: 'las la-exclamation-triangle',
  externalLink: 'las la-external-link-square-alt',
  features: 'las la-flag',
  home: 'las la-home',
  info: 'las la-info-circle',
  link: 'las la-link',
  mapMarked: 'las la-map-marked',
  mountain: 'las la-mountain',
  plus: 'las la-plus',
  plusCircle: 'las la-plus-circle',
  projects: 'las la-cubes',
  releases: 'las la-code-branch',
  remove: 'las la-minus',
  shippingFast: 'las la-shipping-fast',
  spinner: 'las la-circle-notch',
  stream: 'las la-stream',
  success: 'las la-check-circle',
  tasks: 'las la-tasks',
  timesCircle: 'las la-times-circle',
  undo: 'las la-undo-alt',
  user: 'las la-user',
  variables: 'las la-tags',
  warning: 'las la-exclamation-circle',
};
